### ISSUE TITLE
cordova.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by andrewvmail** [Rudy-Zidan/inferno-mobile#2]
Tried to run but at the browser console got error message...

**Comment by pushpendra-jaypore** [comment]
same issue here

**Comment by Draisdale** [comment]
I have the same issue can someone please tell us how to fix it

**Comment by evinkuraga** [comment]
same here

**Comment by evinkuraga** [comment]
For those of you still landing on this page, for me it had to do with the incorrect file location of the cordova.js file when using extra route parameters. I fixed it by adding a / to the cordovaLoader.js file 

`return `/cordova/${platform}/platform_www/cordova.js`;`
